name: Validate config.json

on: [push, pull_request]

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          npm install -g ajv-cli
          ajv validate -s config.json -d config.json
